/**
 * Representation of a DocuSign Agreement status.
 */
public class AgreementStatus {

    public static final String NEW_AGREEMENT = 'NEW';
    public static final String NEW_VERSION = 'NEW VERSION';

    public static final String PENDING_REVIEW = 'PENDING REVIEW';
    public static final String REVIEWED = 'REVIEWED';
    public static final String REVIEW_CANCELLED = 'REVIEW CANCELLED';
    public static final String REVIEWED_EXPIRED = 'REVIEWED EXPIRED ';

    public static final String PENDING_APPROVAL = 'PENDING APPROVAL';
    public static final String APPROVED = 'APPROVED';
    public static final String APPROVAL_CANCELLED = 'APPROVAL CANCELLED';
    public static final String COMPLETED = 'COMPLETED';

    public static final String REJECTED = 'REJECTED';
    public static final String SIGNED = 'SIGNED';
    public static final String SIGNATURE_CANCELLED = 'SIGNATURE CANCELLED';
    public static final String NO_STATUS = 'NO STATUS';
    public static final String PENDING_SIGNATURE = 'PENDING SIGNATURE';
    
}